export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PROFIL_UPDATED="PROFIL_UPDATED";
export const INI_UPDATE="INI_UPDATE";
export const SET_SEARCH="SET_SEARCH"
export const INI_SEARCH="INI_SEARCH"
export const GET_EVENTS ="GET_EVENTS"